#redis:
#  host: localhost
#  port: 6379
#  masterName: redismaster
#  password: testredis@123
#  hostMaster: 10.22.7.111
#  portMaster: 26379
#  hostSlave: 10.22.7.112
#  portSlave: 26379

spring:
  datasource:
    url: jdbc:oracle:thin:@10.22.7.63:1521/GTGTTEST
    username: mms
    password: mms
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 29
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: pool1
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: testredis@123
    lettuce:
      pool:
        max-active: 30
        max-idle: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs: 60000
    sentinel:
      password: testredis@123
      nodes:
        - 10.20.27.20:6379
        - 10.22.7.112:26379
      master: redismaster
    connect-timeout: 500000




