#redis:
#  host: localhost
#  port: 6379
#  masterName: redismaster
#  password: testredis@123
#  hostMaster: 10.22.7.111
#  portMaster: 26379
#  hostSlave: 10.22.7.112
#  portSlave: 26379

server:
  port: 8080
spring:
  rabbitmq:
    host: 10.22.7.88
    port: 6789
    username: qrcode
    password: qrcode
    #    requested-heartbeat thuong co value : 5 -> 20 (second)
    requested-heartbeat: 15
    virtual-host: qrcode
  datasource:
    url: jdbc:oracle:thin:@10.22.7.63:1521/GTGTTEST
    username: mms
    password: mms
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 29
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: pool1
  redis:
    database: 0
    password: testredis@123
    lettuce:
      pool:
        max-active: 30
        max-idle: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs: 60000
#    sentinel:
#      master: redismaster
#      nodes:
#        - 10.22.7.111:26379
#        - 10.22.7.112:26379
    connect-timeout: 500000
    port: 6379
    host: localhost
rabbitMQ:
  toppicExchangeName: exchange-one
  queueName: tien.test.qrcode.2
  routingKey: routing.*
  routingKeyOne: routing.one
